package com.codeup.codeupspringblog.models;

import jakarta.persistence.*;
// This annotation marks the class as an entity, meaning it is a table in a relational database.

@Entity
// This annotation specifies the name of the table in the database that will store the entity.

@Table(name = "posts")
public class Post {
    // This annotation specifies that the field is the primary key of the table.
    @Id
    //This annotation is used to configure the way that the ID field is generated. In this case, GenerationType.IDENTITY is used to indicate that the primary key value should be generated by the database. This is often used with auto-increment columns in SQL databases.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // This annotation specifies the length of the column in the database and that the column cannot be null.

    @Column(length = 150, nullable = false)
    private String title;
    // This annotation specifies the type of the column as text and that the column cannot be null.

    @Column(columnDefinition = "TEXT NOT NULL")
    private String body;

    public Post() {
    }

    public Post(String title, String body) {
        this.title = title;
        this.body = body;
    }

    public Post(Long id, String title, String body) {
        this.id = id;
        this.title = title;
        this.body = body;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }
}
